from os.path import join as j

# Use a config file
configfile: "config.yaml"

RAW_DIR = j(config["data_dir"], "raw")
DERIVED_DIR = j(config["data_dir"], "derived")
FIG_DIR = j(config["fig_dir"], "figs")

"""
rule all:
    input:
        FIG1

rule figure1:
    input:
        SOME_DATASET
    output:
        FIG1
    shell:
        "python scripts/plot_fig1.py {input} {output}"
"""
